
spring:
  application:
    name: zini-shop
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  batch:
    jdbc:
      initialize-schema: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_MAIL}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
jwt:
  secret: ${JWT_SECRET_KEY}
